### ISSUE TITLE
Alex build failing with missing filepath at preprocessing step

### ISSUE THREAD

**Issue by solomon-b** [haskell/alex#195] opened 2021-11-05 17:09 UTC
I'm not sure if it is relevant but this is on Nixos.
```
➜ cabal build
Build profile: -w ghc-8.10.7 -O1
In order, the following will be built (use -v for more details):
 - alex-3.2.7 (exe:alex) (first run)
Preprocessing executable 'alex' for alex-3.2.7..
alex: /home/solomon/Development/haskell/alex/./data//AlexTemplate-ghc: openFile: does not exist (No such file or directory)
```

That filepath looks odd. Any ideas what might be going wrong?

**Comment by TOTBWF** [comment] 2021-11-08 18:25
I can reproduce this with `cabal build`, however, `stack build` seems to work

**Comment by andreasabel** [comment] 2022-01-22 08:32
I can confirm this problem on macOS Mojave.

**Comment by Ericson2314** [comment] 2022-01-22 17:39
Yes this is a very weird error. I think there is some logic in prior versions of alex to try to use newer templates? But those don't exist because we simplified the templating system.

**Comment by Ericson2314** [comment] 2022-01-23 06:42
BTW if you manually run alex on the file and delete the original `Scan.hs`, it will work. It is just when cabal invokes Alex that weird things happen!

**Comment by Ericson2314** [comment] 2022-01-23 07:23
Ah, this is because the autogenerated `Paths_alex` module allows `alex_` env vars to override the data dirs. During the build those env vars are defined (at least with the latest Cabal), and thus we try to bootstrap feeding the old alex the new alex's templates! :facepalm:

More reason to finish https://github.com/simonmar/alex/pull/174, I suppose.

**Comment by sgraf812** [comment] 2024-06-26 09:09
Is this still a problem? I ran `cabal build` and `cabal test` successfully on `master` (3.5.1).

At any rate, I `happy` suffered from a similar error which can be traced back to `Cabal`; see https://github.com/haskell/happy/issues/274#issuecomment-2152649291.

**Comment by andreasabel** [comment] 2024-06-26 11:31
Let's close this optimistically.

**Closed by andreasabel** 2024-06-26 11:31 UTC
Labels: bug, build / install
